name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_localization: ^0.2.2
  go_router: ^14.3.0
  responsive_framework: ^1.5.1
  hugeicons: ^0.0.7
  ext_plus: ^0.0.9
  el_tooltip: ^2.2.1
  flutter_smart_dialog: ^4.9.8+3
  flutter_acrylic: ^1.1.4
  side_sheet: ^1.0.4
  wolt_modal_sheet:
    path: /Users/electrovese/Downloads/wolt_modal_sheet-main
  demo_ui_components:
    path: /Users/electrovese/Downloads/wolt_modal_sheet-main/demo_ui_components

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Italic-VariableFont_wdth,wght.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf          
          weight: 700
          

